Yogesh :	compile object

compile :
	g++ createkn01.cpp
	g++ bruteforce.cpp
	g++ dynpro.cpp
	g++ backtrack.cpp

object :
	g++ -o createkn01 createkn01.cpp
	g++ -o bruteforce bruteforce.cpp
	g++ -o dynpro dynpro.cpp
	g++ -o backtrack backtrack.cpp
