Yogesh :	compile object

compile :
	g++ Jadhav_Yogesh_pa3_lcs.cpp
	g++ Jadhav_Yogesh_pa3_floyd.cpp

object :
	g++ -o Jadhav_Yogesh_pa3_lcs Jadhav_Yogesh_pa3_lcs.cpp
	g++ -o Jadhav_Yogesh_pa3_floyd Jadhav_Yogesh_pa3_floyd.cpp
